<div class="container mt-4">
<p class="gris-color h2 ml-1"> NUEVO PROVEEDOR </p>
<form action="./agregarProveedor" class="" method="post">
            <div class="form-group ">
                <label for="title" class="" >Nombre</label>
                <input type="text" class="w-50 altura-input ml-5" name="nombreproveedor" value="">
            </div>
            <div class="form-group ">
                <label for="title " class="">Cuil-Cuit</label>
                <input type="text" class="w-75 altura-input ml-4" name="cuil_cuit" value="">
            </div>
            <div class="form-group ">
                <label for="title " class="">Ciudad</label>
                <input type="text" class="w-75 altura-input ml-4" name="ciudad" value="">
            </div>
            <div class="form-group ">
                <label for="title " class="">Telefono</label>
                <input type="text" class="w-75 altura-input ml-4" name="telefono" value="">
            </div>
            <button type="submit" class="btn btn-primary bg-dark">Agregar</button>
            </div>
    </form>
    
    </div>