<!DOCTYPE html>
<html lang="es" data-bs-theme="dark">
<head>
    <base href="<?= BASE_URL ?>">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TPE Especial</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/header.css">    
    
</head>
<body>
    <header class="container-fluid py-3">
        <h1 class="text-center"> MERCADO JUVI</h1>
    </header>

    <nav class="navbar navbar-expand-lg navbar-dark">
        
        <?php if($this->user): ?>
                    <span class="navbar-brand">Bienvenido: <?= htmlspecialchars($this->user->email) ?></span>
                <?php endif; ?>

        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="./productos">Productos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="./proveedores">Proveedores</a>
                </li>
                <?php if ($this->user):?>             
             
                <li class="nav-item">
                    <a class="nav-link" href="./logout">LOG OUT</a>
                </li>
                <?php else: ?>  
                    <li class="nav-item">
                    <a class="nav-link" href="./login">LOGIN</a>
                </li>
                <?php endif; ?>   
            </ul>
        </div>
    </nav>




    