<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Supermercado</title>
    <link rel="stylesheet" href="./css/header.css">
</head>
<body>
    <header>
        <div class="logo">Supermercado XYZ</div>
        <nav>
            <a href="#">Inicio</a>
            <a href="./productos">Productos</a>
            <a href="./proveedores">Proveedores</a>
            <a href="./logout">LOG OUT</a>
        </nav>
    </header>