<?=require 'headerLogeado.phtml'?>
<div class="container">

<h2 class="display-4 text-capitalize grey-color container mt-4 mb-4"> Altas </h2> 


    <table class="font-size-tabla  ml-2 mt-4 tabla">
        <th class="th-tipo text-center th-prop th-prop-largo"> ID </th>
        <th class="th-nombre text-center th-prop th-prop-largo ">NOMBRE</th>
        <th class="th-valor text-center th-prop th-acciones "> CATEGORIA </th>
        <th class="th-valor text-center th-prop th-acciones th-borde-right "> </th>

        <?php foreach($productos as $producto) { ?> 
            <tr>
                <td class="td-prop text-center"> <?=$producto->id?> </td>
                <td class="td-prop text-center"> <?=$producto->nombre_producto?> </td>
                <td class="td-prop text-center"> <?=$producto->nombre_categoria?> </td>
                <div class="acciones">
                    <td class="p-0 border-btn "> <a href="producto/<?=$producto->id?>" class="p-1 m-1 bg-dark ancho-ver "> VER </td>
                </div>

        </tr>
        <?php } ?>
    </table>
    
    <form action="./filtrar" class="" method="post">    
                <select name="id_categoria_filtro" id="">
                    <option href="./productos">TODOS</option>
                    <?php foreach($categorias as $categoria) { ?>
                    <option value="<?=$categoria->id?>"><?=$categoria->nombre?></option>
                    <?php } ?>
                </select> 
                <button type="submit" class="btn btn-primary bg-dark">FILTRAR</button>
    </form>

    <div class="container mt-4">

        <p class="gris-color h2 ml-1"> AGREGAR PRODUCTO </p>
        <form action="./agregarProducto" class="" method="post">
            <div class="form-group ">
                <label for="title" class="" >Nombre</label>
                <input type="text" class="w-50 altura-input ml-5" name="new_nombre" value="">
            </div>
            <div class="form-group ">
                <label for="title " class="">Descripcion</label>
                <select name="new_id_proveedor" id="">
                    <?php foreach($proveedores as $proveedor) { ?>
                    <option value="<?=$proveedor->id?>"><?=$proveedor->nombre?></option>
                    <?php } ?>
                </select>
                <select name="new_id_medida" id="">
                    <?php foreach($medidas as $medida) { ?>
                    <option value="<?=$medida->id?>"><?=$medida->unidad_medida?></option>
                    <?php } ?>
                </select>
                <select name="new_id_categoria" id="">
                    <?php foreach($categorias as $categoria) { ?>
                    <option value="<?=$categoria->id?>"><?=$categoria->nombre?></option>
                    <?php } ?>
                </select>
            </div>
            <button type="submit" class="btn btn-primary bg-dark">Ingresar</button>
            </div>
        </form>
</div>
</div>
