<?=require 'header.phtml'?>

<div class="container">

<h2 class="display-4 text-capitalize grey-color container mt-4 mb-4"> Altas </h2> 


    <table class="font-size-tabla  ml-2 mt-4 tabla">
        <th class="th-tipo text-center th-prop th-prop-largo"> ID </th>
        <th class="th-nombre text-center th-prop th-prop-largo ">NOMBRE</th>
        <th class="th-valor text-center th-prop th-acciones "> CATEGORIA </th>
        <th class="th-valor text-center th-prop th-acciones th-borde-right "> </th>

        <?php foreach($productos as $producto) { ?> 
            <tr>
                <td class="td-prop text-center"> <?=$producto->id?> </td>
                <td class="td-prop text-center"> <?=$producto->nombre_producto?> </td>
                <td class="td-prop text-center"> <?=$producto->nombre_categoria?> </td>
                <div class="acciones">
                    <td class="p-0 border-btn "> <a href="producto/<?=$producto->id?>" class="p-1 m-1 bg-dark ancho-ver "> VER </td>
                </div>

        </tr>
        <?php } ?>
    </table>
    
    <form action="./filtrar" class="" method="post">    
                <select name="id_categoria_filtro" id="">
                    <option href="./productos">TODOS</option>
                    <?php foreach($categorias as $categoria) { ?>
                    <option value="<?=$categoria->id?>"><?=$categoria->nombre?></option>
                    <?php } ?>
                </select> 
                <button type="submit" class="btn btn-primary bg-dark">FILTRAR</button>
    </form>

    <div class="container mt-4">

</div>
</div>
<?=require 'footer.phtml'?>
