<?=require 'header.phtml'?>

<div class="container">

<h2 class="display-4 text-capitalize grey-color container mt-4 mb-4"> Altas </h2> 


    <table class="font-size-tabla  ml-2 mt-4 tabla">
        <th class="th-tipo text-center th-prop th-prop-largo"> ID </th>
        <th class="th-nombre text-center th-prop th-prop-largo ">NOMBRE</th>
        <th class="th-valor text-center th-prop th-acciones "> CUIL_CUIT </th>
        <th class="th-valor text-center th-prop th-acciones "> CIUDAD </th>
        <th class="th-valor text-center th-prop th-acciones "> TELEFONO </th>
        <th class="th-valor text-center th-prop th-acciones th-borde-right "> </th>

        <?php foreach($proveedor as $prv) { ?> 
            <tr>
                <td class="td-prop text-center"> <?=$prv->id?> </td>
                <td class="td-prop text-center"> <?=$prv->nombre?> </td>
                <td class="td-prop text-center"> <?=$prv->cuil_cuit?> </td>
                <td class="td-prop text-center"> <?=$prv->ciudad?> </td>
                <td class="td-prop text-center"> <?=$prv->telefono?> </td>
                
                <?php if ($this->user):?>
                <div class="acciones">
                    <td class="p-0 border-btn "> <a href="./modificarProveedor/<?=$prv->id?>" class="p-1 m-1 bg-dark ancho-modif"> MODIFICAR </td>
                    <td class="p-0 th-borde-right border-btn"> <a href="./deleteProveedor/<?=$prv->id?>" class=" p-1 m-1 bg-dark ancho-ver"> ELIMINAR </td> 
                </div>
                <?php endif;?>

        </tr>
        <?php } ?>
    </table>

</div>
</div>
<?=require 'footer.phtml'?>
